export const cards = [
  {
    id: 1,
    pairId: 1,
    flipped: false,
    path: "../../../assets/images/1.png",
  },
  {
    id: 2,
    pairId: 1,
    flipped: false,
    path: "../../../assets/images/1.png",
  },
  {
    id: 3,
    pairId: 2,
    flipped: false,
    path: "../../../assets/images/2.png",
  },
  {
    id: 4,
    pairId: 2,
    flipped: false,
    path: "../../../assets/images/2.png",
  },
  {
    id: 5,
    pairId: 3,
    flipped: false,
    path: "../../../assets/images/3.png",
  },
  {
    id: 6,
    pairId: 3,
    flipped: false,
    path: "../../../assets/images/3.png",
  },
  {
    id: 7,
    pairId: 5,
    flipped: false,
    path: "../../../assets/images/5.png",
  },
  {
    id: 8,
    pairId: 5,
    flipped: false,
    path: "../../../assets/images/5.png",
  },
  {
    id: 9,
    pairId: 5,
    flipped: false,
    path: "../../../assets/images/5.png",
  },
  {
    id: 10,
    pairId: 5,
    flipped: false,
    path: "../../../assets/images/5.png",
  },
  {
    id: 11,
    pairId: 6,
    flipped: false,
    path: "../../../assets/images/6.png",
  },
  {
    id: 12,
    pairId: 6,
    flipped: false,
    path: "../../../assets/images/6.png",
  },
  {
    id: 13,
    pairId: 7,
    flipped: false,
    path: "../../../assets/images/7.png",
  },
  {
    id: 14,
    pairId: 7,
    flipped: false,
    path: "../../../assets/images/7.png",
  },
  {
    id: 15,
    pairId: 8,
    flipped: false,
    path: "../../../assets/images/8.png",
  },
  {
    id: 16,
    pairId: 8,
    flipped: false,
    path: "../../../assets/images/8.png",
  },
  {
    id: 17,
    pairId: 9,
    flipped: false,
    path: "../../../assets/images/9.png",
  },
  {
    id: 18,
    pairId: 9,
    flipped: false,
    path: "../../../assets/images/9.png",
  },
];
